plugins {
    id 'io.ryoung.java-downloader'
}

repositories {
    mavenLocal()
    maven { url = 'https://repo.runelite.net' }
    mavenCentral()
}

def baseRepoUrl = 'https://raw.githubusercontent.com/melkypie/resource-packs/refs/heads/master'

javaDownload {
    files = [
            [url : "${baseRepoUrl}/src/main/java/melky/resourcepacks/model/runelite/ChatColorKey.java",
             path: 'src/main/java/melky/resourcepacks/model/runelite/ChatColorKey.java'],
            [url : "${baseRepoUrl}/src/main/resources/overrides/overrides.toml",
             path: 'src/main/resources/overrides/overrides.toml'],
            [url : "${baseRepoUrl}/src/main/resources/overrides/vars.toml",
             path: 'src/main/resources/overrides/vars.toml']
    ]
}

dependencies {
    implementation project(':common')
    compileOnly libs.runelite.api
    implementation libs.tomlj
    implementation libs.guava
    implementation libs.slf4j.api
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}

jar {
    manifest {
        attributes  'Main-Class': 'melky.resourcepacks.generator.PackBuilder'
    }
}

tasks.register('generateSamples', JavaExec) {
	mainClass = 'melky.resourcepacks.generator.OverridesBuilder'
	classpath = sourceSets.main.runtimeClasspath
	systemProperty('outputDir', System.getProperty('outputDir', 'out/sample-vanilla'))
	systemProperty('overridesPath', System.getProperty('overridesPath'))
}

tasks.register('generatePack', JavaExec) {
	mainClass = 'melky.resourcepacks.generator.SpriteSyncer'
	classpath = sourceSets.main.runtimeClasspath
	systemProperty('spriteFolder', System.getProperty('spriteFolder'))
	systemProperty('outputDir', System.getProperty('outputDir', 'sample-pack'))
}

tasks.register('buildPack', JavaExec) {
	mainClass = 'melky.resourcepacks.generator.PackBuilder'
	classpath = sourceSets.main.runtimeClasspath
	systemProperty('spriteFolder', System.getProperty('spriteFolder'))
	systemProperty('outputDir', System.getProperty('outputDir', 'sample-pack'))
	systemProperty('overridesPath', System.getProperty('overridesPath'))
}
