plugins {
    id 'io.ryoung.java-downloader'
}

repositories {
    mavenLocal()
    maven { url = 'https://repo.runelite.net' }
    mavenCentral()
}

def baseRepoUrl = 'https://raw.githubusercontent.com/melkypie/resource-packs/refs/heads/master'

javaDownload {
    files = [
            [url : "${baseRepoUrl}/src/main/java/melky/resourcepacks/model/SpriteOverride.java",
             path: 'src/main/java/melky/resourcepacks/model/SpriteOverride.java']
    ]
}

dependencies {
    compileOnly libs.runelite.api
    implementation libs.guava
    implementation libs.slf4j.api
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}
