plugins {
    id 'io.ryoung.java-downloader'
}

repositories {
    mavenLocal()
    maven { url = 'https://repo.runelite.net' }
    mavenCentral()
}

dependencies {
    implementation project(':common')
    compileOnly libs.runelite.api
    implementation libs.guava
    implementation libs.slf4j.api
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}

jar {
    manifest {
        attributes 'Main-Class': 'melky.resourcepacks.validation.PackCheck'
    }
}

tasks.register('checkPack', JavaExec) {
    mainClass = 'melky.resourcepacks.validation.PackCheck'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty('spriteFolder', System.getProperty('spriteFolder'))
    systemProperty('packFolder', System.getProperty('packFolder'))
}
